### create a new patient enitity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "John Doe with billing account",
  "email": "test_billing_account_09@example.com",
  "address": "123 test address, test City",
  "dateOfBirth": "2000-12-10",
  "registrationDate": "2020-06-11"
}

###