### update existing patient entity
PUT http://localhost:8080/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "Test Update",
  "email": "test_update@example.com",
  "address": "123 test ad, test city",
  "dateOfBirth": "1990-09-23"
}

###