### update existing patient entity
PUT http://localhost:4004/api/patients/5cde276f-f666-45b2-bfd0-05ff9b9ee22a
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Update",
  "email": "test_update_2@example.com",
  "address": "123 test ad, test city",
  "dateOfBirth": "1990-09-23"
}

###