# central configuration file for Spring Boot application
spring.application.name=patient-service


# UNCOMMENT TO USE IN MEMORY DATABASE OUTSIDE OF DOCKER
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## automatically create/update DB tables
#spring.jpa.hibernate.ddl-auto=update
#
## always run SQL files found in resources every time the app starts
#spring.sql.init.mode=always


# Deserialize Kafka message keys into String objects.
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Deserialize Kafka message values into byte arrays for Protobuf parsing.
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
# Serialize Kafka message keys as strings.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Serialize Protocol Buffers byte[] payloads.
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

server.port=4000
logging.level.root=info