name: Patient Service CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -f patient-service/pom.xml -DSkipTests

      - name: Build patient-service
        run: docker build -t patient-service ./patient-service

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push patient-service
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag patient-service ghcr.io/${{ github.repository }}/patient-service:latest
          docker push ghcr.io/${{ github.repository }}/patient-service:latest